### ISSUE TITLE
Incorrect distribution link from pod page

### ISSUE THREAD

**Issue by abh** [metacpan/metacpan-api#1021]
On https://metacpan.org/pod/Beanstalk::Client the breadcrumb link to "Beanstalk-Client-1.07" goes to `https://dist/Beanstalk-Client` rather than the proper relative link.

It looks like the bug is a double `//` prefix in the URL.

**Comment by haarg** [comment]
One of the servers hadn't properly updated to the fixed code. Fixed now.

**Comment by neilb** [comment]
I'm still getting this, for example on https://metacpan.org/pod/Lab::Measurement, but I don't a dodgy URL when looking at https://metacpan.org/pod/Dist::Zilla

Caching?

**Comment by haarg** [comment]
That's probably caching in your browser.

**Comment by oalders** [comment]
Not the answer you're looking for, but `curl -XPURGE  https://metacpan.org/pod/Lab::Measurement` can clear up individual pages. That's a good way to check if the issue is at the Fastly layer.

**Comment by haarg** [comment]
Fixed.
